// 13 GIFs with real captions from both models (generated by run_captions.py).
// Fine-tuned = Patricijia/smolvlm-gif-descriptor
// Base       = HuggingFaceTB/SmolVLM-256M-Instruct
const EXAMPLES = [
  {
    gif: 'https://media3.giphy.com/media/v1.Y2lkPWVjOWY5Nzk1NWljejR4ZGR2cnI3aW9xb2YyamVrb2kwM20zaHQxeXhoaDk1MGZzNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/F0Z9Fi4eB4YXr4FURN/giphy.gif',
    title: 'Coffee Overacting',
    finetuned: 'A man with hair on his head is holding a cup of coffee.',
    base: 'A new shirt was laid on top of it for him today he walked all around with his hands together like this one is doing something funny. He had',
  },
  {
    gif: 'https://media4.giphy.com/media/v1.Y2lkPWVjOWY5Nzk1NWljejR4ZGR2cnI3aW9xb2YyamVrb2kwM20zaHQxeXhoaDk1MGZzNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/6US0tgDSoDscX23dJT/giphy.gif',
    title: 'Looking English',
    finetuned: 'A girl with purple hair is looking at something.',
    base: '[2]',
  },
  {
    gif: 'https://media2.giphy.com/media/v1.Y2lkPWVjOWY5Nzk1NWljejR4ZGR2cnI3aW9xb2YyamVrb2kwM20zaHQxeXhoaDk1MGZzNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/gj0QdZ9FgqGhOBNlFS/giphy.gif',
    title: 'Cracking Up Lol',
    finetuned: 'A baby is laughing and then looks down.',
    base: 'Yes.',
  },
  {
    gif: 'https://media0.giphy.com/media/v1.Y2lkPWVjOWY5Nzk1NWljejR4ZGR2cnI3aW9xb2YyamVrb2kwM20zaHQxeXhoaDk1MGZzNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/v8r6BD3hWYG7PybeKJ/giphy.gif',
    title: 'Get Money Bitcoin',
    finetuned: 'An old woman is reading a book while writing notes on a table.',
    base: 'Countdown Total is equal to 24.',
  },
  {
    gif: 'https://media4.giphy.com/media/v1.Y2lkPWVjOWY5Nzk1NWljejR4ZGR2cnI3aW9xb2YyamVrb2kwM20zaHQxeXhoaDk1MGZzNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/tSSMsM330qBoOXTQGc/giphy.gif',
    title: 'Suspicious Bro',
    finetuned: 'A black man is looking at something with an angry expression on his face.',
    base: 'A man walks across the room.',
  },
  {
    gif: 'https://media2.giphy.com/media/v1.Y2lkPWVjOWY5Nzk1NWljejR4ZGR2cnI3aW9xb2YyamVrb2kwM20zaHQxeXhoaDk1MGZzNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/nyg8MJlnSXwUiqM42H/giphy.gif',
    title: 'Laugh Out Loud',
    finetuned: 'A woman is drinking from a cup while another person looks at her with disgust.',
    base: 'SIPPING Drunk Laughing',
  },
  {
    gif: 'https://media2.giphy.com/media/v1.Y2lkPWVjOWY5Nzk1NWljejR4ZGR2cnI3aW9xb2YyamVrb2kwM20zaHQxeXhoaDk1MGZzNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/Zm9inSILc3HHfuXDNy/giphy.gif',
    title: 'Reaction GIF',
    finetuned: 'A man is talking into his phone while standing next to a brick wall.',
    base: '[2]',
  },
  {
    gif: 'https://media4.giphy.com/media/v1.Y2lkPWVjOWY5Nzk1NWljejR4ZGR2cnI3aW9xb2YyamVrb2kwM20zaHQxeXhoaDk1MGZzNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/1nfwnYf5Uz7hzhYof8/giphy.gif',
    title: 'Funny Face Eye Roll',
    finetuned: 'A little girl is drinking from a green bottle.',
    base: 'The boy looks at his phone with an angry expression on his face.',
  },
  {
    gif: 'https://media0.giphy.com/media/v1.Y2lkPWVjOWY5Nzk1NWljejR4ZGR2cnI3aW9xb2YyamVrb2kwM20zaHQxeXhoaDk1MGZzNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/LUTa1Nlzg40D0Y0jNz/giphy.gif',
    title: 'Oggy and the Cockroaches',
    finetuned: 'A green cat is sitting on top of a couch and holding an orange beer bottle with his paws.',
    base: '[5] Each frame shows an angry cat sitting up its back with one arm raised as if it is yelling or shouting something.',
  },
  {
    gif: 'https://media0.giphy.com/media/v1.Y2lkPWVjOWY5Nzk1NWljejR4ZGR2cnI3aW9xb2YyamVrb2kwM20zaHQxeXhoaDk1MGZzNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3MQbWLriSG10UBdAbm/giphy.gif',
    title: 'Comedy Sketch — Netflix',
    finetuned: 'A woman is talking to a man who looks at her with an angry expression on his face.',
    base: 'This is a betrayal on levels that no one\'s ever seen.',
  },
  {
    gif: 'https://media2.giphy.com/media/v1.Y2lkPWVjOWY5Nzk1NWljejR4ZGR2cnI3aW9xb2YyamVrb2kwM20zaHQxeXhoaDk1MGZzNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/nZcQDtarJrTjQp6sWU/giphy.gif',
    title: 'Trying Not to Laugh',
    finetuned: 'A man is smiling and laughing at something.',
    base: 'I just can\'t...I just cant…I only have one job!',
  },
  {
    gif: 'https://media3.giphy.com/media/v1.Y2lkPWVjOWY5Nzk1NWljejR4ZGR2cnI3aW9xb2YyamVrb2kwM20zaHQxeXhoaDk1MGZzNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/gDHo2WqIP8vVOCwlcq/giphy.gif',
    title: 'Louis Mustillo Summer',
    finetuned: 'A man is sitting on a chair with his head covered by a blue umbrella.',
    base: '[2]  3   4    5     6      7        8         9       10          11        12           13',
  },
  {
    gif: 'https://media3.giphy.com/media/v1.Y2lkPWVjOWY5Nzk1NWljejR4ZGR2cnI3aW9xb2YyamVrb2kwM20zaHQxeXhoaDk1MGZzNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/OkqRMxstkC865BG9xa/giphy.gif',
    title: 'Funny Reaction',
    finetuned: 'A little boy is smiling and looking up at something with his mouth open.',
    base: 'Yes.',
  },
];

function buildCard(example, index) {
  const card = document.createElement('div');
  card.className = 'gif-card';

  const img = document.createElement('img');
  img.src = example.gif;
  img.alt = example.finetuned;
  img.loading = index < 4 ? 'eager' : 'lazy';

  const header = document.createElement('div');
  header.className = 'gif-title';
  header.textContent = example.title;

  const captions = document.createElement('div');
  captions.className = 'gif-captions';
  captions.innerHTML = `
    <div class="caption-row">
      <span class="caption-label label-finetuned">Fine-tuned model</span>
      <span class="caption-text">"${example.finetuned}"</span>
    </div>
    <div class="caption-row">
      <span class="caption-label label-base">Base model</span>
      <span class="caption-text">"${example.base}"</span>
    </div>
  `;

  card.appendChild(img);
  card.appendChild(header);
  card.appendChild(captions);
  return card;
}

const grid = document.getElementById('gif-grid');
EXAMPLES.forEach((ex, i) => grid.appendChild(buildCard(ex, i)));
